export default [
    {
      id: 1,
      Name: "Frances Gregory",
      Category: "Business",
      Amount: "N60000",
      DueDate: "12th Aug. 2023",
      Status: "Approved",
    },
    {
      id: 2,
      Name: "Frances Gregory",
      Category: "Business",
      Amount: "N60000",
      DueDate: "12th Aug. 2023",
      Status: "Approved",
    },
    {
      id: 3,
      Name: "Frances Gregory",
      Category: "Business",
      Amount: "N60000",
      DueDate: "12th Aug. 2023",
      Status: "Delined",
    },
    {
      id: 4,
      Name: "Frances Gregory",
      Category: "Personal",
      Amount: "N60000",
      DueDate: "12th Aug. 2023",
      Status: "Declined",
    },
    {
      id: 5,
      Name: "Frances Gregory",
      Category: "Personal",
      Amount: "N60000",
      DueDate: "12th Aug. 2023",
      Status: "Approved",
    },
    {
      id: 6,
      Name: "Frances Gregory",
      Category: "Personal",
      Amount: "N60000",
      DueDate: "12th Aug 2023",
      Status: "Approved",
    },
    {
      id: 7,
      Name: "Frances Gregory",
      Category: "Personal",
      Amount: "N60000",
      DueDate: "12th Aug. 2023",
      Status: "Approved",
    },
    {
      id: 8,
      Name: "Frances Gregory",
      Category: "Personal",
      Amount: "N60000",
      DueDate: "12th Aug. 2023",
      Status: "Declined",
    },   {
      id: 9,
      Name: "Frances Gregory",
      Category: "Personal",
      Amount: "N60000",
      DueDate: "12th Aug. 2023",
      Status: "Approved",
    },
    {
      id: 10,
      Name: "Frances Gregory",
      Category: "Personal",
      Amount: "N60000",
      DueDate: "12th Aug. 2023",
      Status: "Approved",
    },
    {
      id: 11,
      Name: "Frances Gregory",
      Category: "Personal",
      Amount: "N60000",
      DueDate: "12th Aug. 2023",
      Status: "Declined",
    },
    {
      id: 12,
      Name: "Frances Gregory",
      Category: "Personal",
      Amount: "N60000",
      DueDate: "12th Aug. 2023",
      Status: "Declined",
    },  
     {
      id: 13,
      Name: "Frances Gregory",
      Category: "Personal",
      Amount: "N60000",
      DueDate: "12th Aug. 2023",
      Status: "Approved",
    },
    {
      id: 14,
      Name: "Frances Gregory",
      Category: "Personal",
      Amount: "N60000",
      DueDate: "12th Aug. 2023",
      Status: "Declined",
    },
    {
      id: 15,
      Name: "Frances Gregory",
      Category: "Personal",
      Amount: "N60000",
      DueDate: "12th Aug. 2023",
      Status: "Approved",
    },
    {
      id: 16,
      Name: "Frances Gregory",
      Category: "Personal",
      Amount: "N60000",
      DueDate: "12th Aug. 2023",
      Status: "Approved",
    },
    {
      id: 17,
      Name: "Frances Gregory",
      Category: "Personal",
      Amount: "N60000",
      DueDate: "12th Aug. 2023",
      Status: "Delined",
    },
    {
      id: 18,
      Name: "Frances Gregory",
      Category: "Personal",
      Amount: "N60000",
      DueDate: "12th Aug. 2023",
      Status: "Approved",
    },
  ];